name: movie_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.0
dependencies:
  another_flushbar: ^1.12.30
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  device_preview: ^1.2.0
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_native_splash: ^2.4.5
  font_awesome_flutter: ^10.8.0
  path_provider: ^2.1.5
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
dev_dependencies:
  build_runner: ^2.4.13
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
flutter_assets:
  assets_path: assets/images/
  output_path: lib/utils/
  filename: assets.dart
  field_prefix: null
