name: movie_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.5
  dio: ^5.8.0+1
  font_awesome_flutter: ^10.8.0
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  flutter_bloc: ^9.1.0
  bloc: ^9.0.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  path_provider: ^2.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
flutter_assets:
  assets_path: assets/images/
  output_path: lib/utils/
  filename: assets.dart
  field_prefix: